<a href="https://colab.research.google.com/github/KuroShiroe/ml-class/blob/main/Christopher_Puglisi_Bach_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [259]:
import pandas as pd

bach1 = pd.read_csv('bach.csv')
bach = bach1.drop('choral_ID', axis=1)
bach

,event_number,C,C#,D,D#,E,F,F#,G,G#,A,A#,B,bass,meter,chord_label
0,1,YES,NO,NO,NO,NO,YES,NO,NO,NO,YES,NO,NO,F,3,F_M
1,2,YES,NO,NO,NO,YES,NO,NO,YES,NO,NO,NO,NO,E,5,C_M
2,3,YES,NO,NO,NO,YES,NO,NO,YES,NO,NO,NO,NO,E,2,C_M
3,4,YES,NO,NO,NO,NO,YES,NO,NO,NO,YES,NO,NO,F,3,F_M
4,5,YES,NO,NO,NO,NO,YES,NO,NO,NO,YES,NO,NO,F,2,F_M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5660,105,NO,NO,YES,NO,NO,NO,NO,YES,NO,NO,YES,NO,G,4,G_m
5661,106,NO,NO,YES,NO,NO,NO,NO,YES,NO,YES,NO,NO,G,3,G_m
5662,107,YES,NO,NO,NO,YES,NO,NO,YES,NO,NO,NO,NO,C,5,C_M
5663,108,YES,NO,NO,NO,YES,NO,NO,YES,NO,NO,YES,NO,C,3,C_M
5664,109,NO,NO,NO,NO,NO,YES,NO,NO,NO,YES,NO,NO,F,4,F_M

In [260]:
bach = pd.concat([pd.get_dummies(bach[['C','C#', 'D',	'D#',	'E',	'F',	'F#',	'G',	'G#',	'A',	'A#',	'B']]), bach[['chord_label']]], axis=1)
bach

,C_NO,C_YES,C#_NO,C#_YES,D_NO,D_YES,D#_NO,D#_YES,E_NO,E_YES,...,G_YES,G#_NO,G#_YES,A_NO,A_YES,A#_NO,A#_YES,B_NO,B_YES,chord_label
0,0,1,1,0,1,0,1,0,1,0,...,0,1,0,0,1,1,0,1,0,F_M
1,0,1,1,0,1,0,1,0,0,1,...,1,1,0,1,0,1,0,1,0,C_M
2,0,1,1,0,1,0,1,0,0,1,...,1,1,0,1,0,1,0,1,0,C_M
3,0,1,1,0,1,0,1,0,1,0,...,0,1,0,0,1,1,0,1,0,F_M
4,0,1,1,0,1,0,1,0,1,0,...,0,1,0,0,1,1,0,1,0,F_M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5660,1,0,1,0,0,1,1,0,1,0,...,1,1,0,1,0,0,1,1,0,G_m
5661,1,0,1,0,0,1,1,0,1,0,...,1,1,0,0,1,1,0,1,0,G_m
5662,0,1,1,0,1,0,1,0,0,1,...,1,1,0,1,0,1,0,1,0,C_M
5663,0,1,1,0,1,0,1,0,0,1,...,1,1,0,1,0,0,1,1,0,C_M
5664,1,0,1,0,1,0,1,0,1,0,...,0,1,0,0,1,1,0,1,0,F_M

In [261]:
bFeatures = bach.drop('chord_label', axis=1)
bLabels = bach['chord_label']
from sklearn.model_selection import train_test_split
bach_train_features, bach_test_features, bach_train_labels, bach_test_labels = train_test_split(bFeatures, bLabels, test_size = 0.2, random_state=42)

In [292]:
from numpy.random.mtrand import rand
from sklearn import tree
cls = tree.DecisionTreeClassifier(criterion='entropy', max_depth = 13, random_state = 0)
cls.fit(bach_train_features, bach_train_labels)

DecisionTreeClassifier(criterion='entropy', max_depth=13, random_state=0)

In [293]:
bach_predictions = cls.predict(bach_test_features)
from sklearn.metrics import accuracy_score
accuracy_score(bach_test_labels, bach_predictions)

0.6919682259488085